#!/bin/bash

# Simulate the behavior of 'ls' with some sample files and directories
echo "AUTHORS"
echo "README.md"
echo "alias.c"
echo "allowed_functions"
echo "bin_ls.bash"
echo "checker.bash"
echo "entry_point_file.c"
echo "environment.c"
echo "execution.c"
echo "exit_file.c"
echo "forEnv.c"
echo "free_par.c"
echo "getline_file.c"
echo "hsh"
echo "moved"
echo "my_shell"
echo "path_file.c"
echo "print_file.c"
echo "promptshow_file.c"
echo "readuserinput_file.c"
echo "shell.h"
echo "tockenization_file.c"
echo "tokens.c"
echo "vgcore.3021"
